name: Set Up Web Export Template Dependencies
description: Sets up dependencies for the web export templates.

inputs:
  editor-artifact-name:
    description: Editor artifact name containing glue and version metadata.
    required: true

runs:
  using: composite

  steps:
    - name: Set Up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
      with:
        python-version: 3.x

    - name: Set Up WASM Tools
      shell: bash
      run: |
        # Install wasm-tools for both 10.0 and 9.0 SDKs
        if [[ -f global.json ]]; then
          mv global.json global.json.disabled
        fi
        dotnet workload install wasm-tools

        if [[ -f global.json.disabled ]]; then
          mv global.json.disabled global.json
          dotnet workload install wasm-tools
        fi

    - name: Set Up SCons (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install scons -y

    - name: Set Up SCons (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew install scons

    - name: Set Up SCons (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        python -m pip install scons

    - name: Set Up Emscripten SDK
      uses: mymindstorm/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 #v16

    - name: Download Artifacts From Editor Build
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
      with:
        name: ${{ inputs.editor-artifact-name }}
        path: godot/bin

    - name: Copy Mono Glue
      shell: bash
      run: cp -rf godot/bin/glue/* godot/modules/mono/glue

    - name: Build Mono Assemblies
      shell: bash
      run: python godot/modules/mono/build_scripts/build_assemblies.py --godot-output-dir=godot/bin --push-nupkgs-local godot/bin/nuget